// Custom sync
user_pref('services.sync.engine.bookmarks', false);
user_pref('services.sync.prefs.sync.browser.aboutConfig.showWarning', true);
user_pref('services.sync.prefs.sync.browser.download.lastDir.savePerSite', true);
user_pref('services.sync.prefs.sync.browser.search.suggest.enabled.private', true);
user_pref('services.sync.prefs.sync.browser.toolbars.bookmarks.visibility', true);
user_pref('services.sync.prefs.sync.browser.uiCustomization.state', true);
user_pref('services.sync.prefs.sync.findbar.highlightAll', true);
user_pref('services.sync.prefs.sync.full-screen-api.transition.timeout', true);
user_pref('services.sync.prefs.sync.full-screen-api.transition-duration.enter', true);
user_pref('services.sync.prefs.sync.full-screen-api.transition-duration.leave', true);
user_pref('services.sync.prefs.sync.full-screen-api.warning.delay', true);
user_pref('services.sync.prefs.sync.full-screen-api.warning.timeout', true);
user_pref('services.sync.prefs.sync.toolkit.legacyUserProfileCustomization.stylesheets', true);

// Custom sync backup
// user_pref('app.shield.optoutstudies.enabled', false);
// user_pref('browser.aboutConfig.showWarning', false);
// user_pref('browser.crashReports.unsubmittedCheck.autoSubmit2', false);
// user_pref('browser.discover.enabled', false);
// user_pref('browser.download.lastDir.savePerSite', false);
// user_pref('browser.download.useDownloadDir', false);
// user_pref('browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons', false);
// user_pref('browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features', false);
// user_pref('browser.newtabpage.activity-stream.feeds.section.highlights', false);
// user_pref('browser.newtabpage.activity-stream.feeds.section.topstores', false);
// user_pref('browser.newtabpage.activity-stream.feeds.snippets', false);
// user_pref('browser.newtabpage.activity-stream.feeds.topsites', false);
// user_pref('browser.pageActions.persistedActions', 'value');
// user_pref('browser.search.suggest.enabled.private', true);
// user_pref('browser.startup.homepage', 'about:newtab');
// user_pref('browser.tabs.warnOnClose', false);
// user_pref('browser.toolbars.bookmarks.visibility', 'always');
// user_pref('browser.uiCustomization.state', 'value');
// user_pref('browser.urlbar.suggest.openpage', false);
// user_pref('browser.urlbar.suggest.topsites', false);
// user_pref('findbar.highlightAll', true);
// user_pref('full-screen-api.transition.timeout', '0');
// user_pref('full-screen-api.transition-duration.enter', '0 0');
// user_pref('full-screen-api.transition-duration.leave', '0 0');
// user_pref('full-screen-api.warning.delay', '0');
// user_pref('full-screen-api.warning.timeout', '0');
// user_pref('general.autoScroll', true);
// user_pref('general.smoothScroll', false);
// user_pref('media.eme.enabled', true);
// user_pref('network.trr.mode', '2');
// user_pref('signon.autofillForms', false);
// user_pref('signon.generation.enabled', false);
// user_pref('signon.management.page.breach-alerts.enabled', false);
// user_pref('signon.rememberSignons', false);
// user_pref('tool.legacyUserProfileCustomizations.stylesheets', true);
